/**
 * Syllabus Markdown Generator
 * 
 * Generates human-readable syllabus from bundle.
 */

import type { CurriculumBundle } from './exportTypes.js';

/**
 * Generate syllabus markdown
 */
export function generateSyllabus(bundle: CurriculumBundle): string {
  const lines: string[] = [];
  
  // Title
  lines.push(`# ${bundle.title}`);
  lines.push('');
  
  // Metadata
  lines.push('## Bundle Information');
  lines.push('');
  lines.push(`- **Bundle ID**: ${bundle.bundleId}`);
  lines.push(`- **Workspace**: ${bundle.workspace}`);
  lines.push(`- **Version**: ${bundle.version}`);
  lines.push(`- **Generated**: ${new Date(bundle.generatedAt).toLocaleString()}`);
  lines.push('');
  
  // Selection criteria
  if (bundle.selection.levels || bundle.selection.scenarios || bundle.selection.tags) {
    lines.push('## Selection Criteria');
    lines.push('');
    if (bundle.selection.levels) {
      lines.push(`- **Levels**: ${bundle.selection.levels.join(', ')}`);
    }
    if (bundle.selection.scenarios) {
      lines.push(`- **Scenarios**: ${bundle.selection.scenarios.join(', ')}`);
    }
    if (bundle.selection.tags) {
      lines.push(`- **Tags**: ${bundle.selection.tags.join(', ')}`);
    }
    lines.push('');
  }
  
  // Totals
  lines.push('## Bundle Totals');
  lines.push('');
  lines.push(`- **Total Packs**: ${bundle.totals.packs}`);
  lines.push(`- **Total Drills**: ${bundle.totals.drills}`);
  lines.push(`- **Total Exams**: ${bundle.totals.exams}`);
  lines.push(`- **Estimated Time**: ${bundle.totals.estimatedMinutes} minutes`);
  lines.push('');
  
  // Modules
  lines.push('## Modules');
  lines.push('');
  
  for (const module of bundle.modules) {
    lines.push(`### ${module.title} (${module.id})`);
    lines.push('');
    
    // Group items by kind
    const packs = module.items.filter(i => i.kind === 'pack');
    const drills = module.items.filter(i => i.kind === 'drill');
    const exams = module.items.filter(i => i.kind === 'exam');
    
    if (packs.length > 0) {
      lines.push('#### Context Packs');
      lines.push('');
      for (const item of packs) {
        lines.push(`- **${item.title}** (${item.id})`);
        if (item.level) {
          lines.push(`  - Level: ${item.level}`);
        }
        if (item.scenario) {
          lines.push(`  - Scenario: ${item.scenario}`);
        }
        if (item.estimatedMinutes) {
          lines.push(`  - Estimated Time: ${item.estimatedMinutes} minutes`);
        }
        if (item.whyThisWorks?.primaryStructure) {
          lines.push(`  - Primary Structure: ${item.whyThisWorks.primaryStructure}`);
        }
        lines.push('');
      }
    }
    
    if (drills.length > 0) {
      lines.push('#### Mechanics Drills');
      lines.push('');
      for (const item of drills) {
        lines.push(`- **${item.title}** (${item.id})`);
        if (item.level) {
          lines.push(`  - Level: ${item.level}`);
        }
        if (item.estimatedMinutes) {
          lines.push(`  - Estimated Time: ${item.estimatedMinutes} minutes`);
        }
        lines.push('');
      }
    }
    
    if (exams.length > 0) {
      lines.push('#### Exams');
      lines.push('');
      for (const item of exams) {
        lines.push(`- **${item.title}** (${item.id})`);
        if (item.level) {
          lines.push(`  - Level: ${item.level}`);
        }
        if (item.estimatedMinutes) {
          lines.push(`  - Estimated Time: ${item.estimatedMinutes} minutes`);
        }
        lines.push('');
      }
    }
  }
  
  // Footer
  lines.push('---');
  lines.push('');
  lines.push(`*Generated by GetVerba Content Pipeline*`);
  lines.push(`*Bundle ID: ${bundle.bundleId}*`);
  
  return lines.join('\n');
}

